language: c
sudo: required
dist: xenial

compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y libusb-dev librtlsdr-dev libfftw3-dev

script:
  - |
    mkdir build
    cd build
    cmake ..
    make
