language: c
sudo: required
dist: xenial

compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y libfftw3-dev librtlsdr-dev libusb-1.0-0-dev pkg-config

script:
  - |
    mkdir build
    cd build
    cmake ..
    make
